name: Radiomap CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Linter (ESLint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  check-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  check-branch-sync:
    name: Check if Branch is Synced with Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if branch is up-to-date with main
        run: |
          git fetch origin main
          LOCAL_COMMIT=$(git rev-parse HEAD)
          MAIN_COMMIT=$(git rev-parse origin/main)

          if [ "$LOCAL_COMMIT" = "$MAIN_COMMIT" ]; then
            echo "✅ Branch is up-to-date with main."
          else
            echo "❌ Branch is NOT up-to-date with main. Please rebase or merge main."
            exit 1
          fi
